### ISSUE TITLE
Tighter integration with Extensions.DependencyInjection

### ISSUE THREAD

**Issue by kpko** [akkadotnet/Akka.Hosting#144]
**Is your feature request related to a problem? Please describe.**
I'm trying out Akka.Hosting in my ASP.NET application and for most parts I'm very happy and didnt need to use any HOCON fine tuning. As a ASP.NET user I'm a bit confused at the state of DependencyInjection when using AddAkka and ActorRegistry. From my past experience with Akka.net I know I can use the DependencyResolver and build props using it to spawn an actor using constructor injection but I have no reference to the DependencyResolver (or the Actor System) in my AddAkka call, right?

Let's say I want to add a cluster singleton via WithSingleton:
```csharp
services.AddAkka(name, (akka, provider) => {
   ...
   akka.WithSingleton<ClusterCronJobSchedulerActor>("cron-scheduler", Props.Create<ClusterCronJobSchedulerActor>());
   ...
});
```

Here I would like to use the "DI-enabled" props via DependencyResolver but I have no reference to the ActorSystem to create my DependencyResolver. I could use WithActors but this defeats the purpose of WithSingleton. Am I doing something wrong here?

**Describe the solution you'd like**
My ideal solution would be one where I didn't have to think about when to use DependencyResolver. My thinking is, when using Akka.Hosting the possibility is high that I also want to be integrated in my ServiceProvider but I expect this isn't possible because we can't just assume constructor injection everywhere as this would make actor creation slower for simple props.

**Describe alternatives you've considered**
My exact problem could be solved by either including ActorSystem/DependencyResolver somewhere in the AddAkka-lambda (akka.System? akka.DependencyResolver? Is the system already available when in building phase?) or providing a factory function everywhere it might be needed (Func<ActorSystem, Props>) to use DependencyResolver.Get(system).

This problem also exists with WithShardRegion calls.

**Comment by Aaronontheweb** [comment]
I think there are some good ideas here - going to noodle on it some and offer up some suggestions. I believe much of what you need to do can be accomplished through the existing lambdas today and I'll include how to do that in my response. cc @kpko

**Comment by kpko** [comment]
Hi Aaron, thanks for looking into this. My workaround now is navigating to the definitions of the extension methods (for example WithSingleton, WithShardRegion) and copying the WithActors-calls into my AddAkka-call to use a reference to the ActorSystem from the WithActor-call. I'm happy to hear that there should be another way of doing this, as this feels kinda hacky and defeating the purpose of the extensions.

Please let me know if theres anything I can help with or if you want me to test something. Thanks again :)

**Comment by Aaronontheweb** [comment]
So we're going to close out this issue today - there are definitely some limitations with the APIs around cluster singletons and cluster sharding that need to be addressed in order to make it easier to access the `ActorSystem` and the `DependencyResolver` when working in those areas.

However, I do want to address this comment and our design philosophy as it pertains to DI and Akka.NET:

> My ideal solution would be one where I didn't have to think about when to use DependencyResolver. My thinking is, when using Akka.Hosting the possibility is high that I also want to be integrated in my ServiceProvider but I expect this isn't possible because we can't just assume constructor injection everywhere as this would make actor creation slower for simple props.

Your assumptions here are correct - for solutions with a large number of actors per-process (i.e. millions running concurrently) this will be noticeably slower, memory-expensive, and probably harder on the GC system. Akka.NET operates at a much larger "object scale" than ASP.NET does, by several orders of magnitude.

For virtually all of our features we try to avoid hidden moving parts that exist without the users' explicit consent, as we believe that approach lends itself to designing more robust, better performing, easier-to-debug applications even if it comes with the upfront cost of a user having to specify how to do something. We think that trade is almost always worth it every time we make it. What we can do here is reduce the effort to make that explicit choice on how an actor is created.

Thank you for taking the time to thoughtfully articulate what you want and to consider our positions too - I really appreciate that. I'll have a draft PR in shortly.

**Comment by Aaronontheweb** [comment]
@kpko you might also be interested in this PR: https://github.com/akkadotnet/Akka.Hosting/pull/170

**Comment by kpko** [comment]
@Aaronontheweb Thank you very much, this looks awesome. I fully agree that Akka operates on a higher scale not suitable for a simple "inject all the things"-strategy. I'm glad you have found a clever way to let us choose how to construct the actor via a more elaborate entityPropsFactory without sacrificing the scalability. :)

 Also, the direct integration into DI via IRequiredActor is great. Thank you again! 👍
