### ISSUE TITLE
Chain of WithActors uses same service collection

### ISSUE THREAD

**Issue by object** [akkadotnet/Akka.Hosting#482]
**Version Information**
Akka.NET version 1.5.27
Which Akka.NET Modules?
Akka.Hosting, Akka.Management

I am not sure this one is a bug, perhaps it was an intention to use the same service resolver while building Akka actors, but in some scenarios it becomes hard to bootstrap the system. Here's ours:

- We are switching from HOCON based configuration to use Akka hosting, so we started using AddAkka extension method
- WithActors call contains registration of a singleton: services.AddSingleton<IRabbitMqApi>(args). If I debug the application, I see that service collection is extended, let's say from 10 to 11 services.
- The boostrapping continues and at some point there is another call to WithActors. This second call resolved IRabbitMqApi instance by calling resolver.GetService<IRabbitMqApi>(). But the call fails - while the application service collection contains 11 services (updated inside the first call to WithActors), the resolver operates on the copy of the services prior the first call to WithActors.

Is this intended that if I chain WithActors multiple times, then its respecitve instances of resolver will use the same copy of service collection, if though there may be new services registered in a call to WithActors? If so, then what is the recommended way to work around this problem?

**Comment by object** [comment]
I discussed this issue on Discord with @Arkatufus, closing this one.

**Comment by Arkatufus** [comment]
For future documentation:

Modifying the `ServiceCollection` inside the `AddAkka()` lambda function is not supported due to how `Microsoft.Extensions.Hosting` pipeline is being called. By the time the lambda function is invoked, the `ServiceCollection` is already built and the resulting `ServiceProvider` is passed into the lambda function.

The solution is to decouple the service and actor creation. Services were to be set-up outside the `AddAkka()` call, If a service requires a reference to an `IActorRef`, then it would inject `IRequiredActor<T>` in their constructor arguments and then to use `IRequiredActor<T>.GetAsync()` to retrieve the actor instance inside the service.
